on: 
  push: 
    paths: 
    - 'jobs/**'
name: Deploy jobs
jobs:
  deploy:
    name: Deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: Deploy to cluster
      uses: gnuu-de/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: rollout restart deployment/job
    - name: Verify deployment
      uses: gnuu-de/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: get pods -l app=job
    - name: Announce deployment
      uses: wei/curl@v1
      env:
        MATRIX_KEY: ${{ secrets.MATRIX_KEY }}
        MATRIX_ROOM: ${{ secrets.MATRIX_ROOM }}
      with:
        args: -d '{\"text\":\"New deployment job done\", \"key\":\"'${MATRIX_KEY}'\", \"room\":\"'${MATRIX_ROOM}'\"}' https://api.gnuu.de/matrixbot/
